# Generated by Django 4.0.2 on 2022-02-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0002_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendinguser',
            old_name='balance',
            new_name='deposit',
        ),
    ]
