# Generated by Django 4.0.2 on 2022-02-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0004_rename_amount_availabe_product_amount_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
